### ISSUE TITLE
CurseForge Port

### ISSUE THREAD

**Issue by moonthecraft** [soapinamicrowave/createworldofcolor#1]
Hello! I'm a fan of the pack and I'm wondering if there will be a CurseForge port so I can include it in a modpack of mine. Thank you! :D

**Comment by soapinamicrowave** [comment]
funnily, i DID consider this a while back! i eventually decided against it because i simply found modrinth's business practices and UX more friendly, but knowing that theres a genuine interest for it i think ill start on making a page for curseforge :D

**Comment by soapinamicrowave** [comment]
waiting on the page to be approved now! will link it here when its up

**Comment by soapinamicrowave** [comment]
here it is! ^^
https://www.curseforge.com/minecraft/texture-packs/create-world-of-color

**Comment by moonthecraft** [comment]
Thanks!
